name:
  build
on:
  push:
    branches:
      - main
      - inject/dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
